import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

// ── Shared helpers ────────────────────────────────────────────────────────────

const addHeader = (doc, title) => {
  // Purple header bar
  doc.setFillColor(124, 106, 247)
  doc.rect(0, 0, 210, 22, 'F')

  // Logo text
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('🧠 StudyBuddy AI', 14, 10)

  // Title
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(title, 14, 17)

  // Date top right
  doc.setFontSize(8)
  doc.text(new Date().toLocaleDateString('en-IN', {
    year: 'numeric', month: 'long', day: 'numeric'
  }), 196, 10, { align: 'right' })

  return 28 // y position after header
}

const addFooter = (doc) => {
  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFillColor(245, 245, 255)
    doc.rect(0, 285, 210, 12, 'F')
    doc.setTextColor(150, 150, 180)
    doc.setFontSize(7)
    doc.text('Generated by StudyBuddy AI — github.com/Twarit01/StudyBuddy', 14, 291)
    doc.text(`Page ${i} of ${pageCount}`, 196, 291, { align: 'right' })
  }
}

const addSectionTitle = (doc, text, y, color = [124, 106, 247]) => {
  doc.setFillColor(...color)
  doc.rect(14, y, 3, 6, 'F')
  doc.setTextColor(30, 30, 60)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text(text, 20, y + 5)
  return y + 10
}


// ── Export Quiz Results ───────────────────────────────────────────────────────

export const exportQuizPDF = ({
  questions,
  answers,
  evaluations,
  score,
  config,
  userName = 'Student'
}) => {
  const doc = new jsPDF()
  let y = addHeader(doc, 'Quiz Results Report')

  // ── Summary box ──
  doc.setFillColor(245, 243, 255)
  doc.roundedRect(14, y, 182, 28, 3, 3, 'F')

  doc.setTextColor(124, 106, 247)
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  const pct = score ? Math.round((score.correct / score.total) * 100) : 0
  doc.text(`${pct}%`, 105, y + 12, { align: 'center' })

  doc.setFontSize(8)
  doc.setTextColor(100, 100, 140)
  doc.setFont('helvetica', 'normal')
  doc.text(`${score?.correct || 0} / ${score?.total || 0} correct`, 105, y + 19, { align: 'center' })
  doc.text(`Topic: ${config?.topic || 'General Engineering'}  |  Type: ${config?.quizType?.toUpperCase() || 'MCQ'}  |  Difficulty: ${config?.difficulty || 'Medium'}  |  Student: ${userName}`, 105, y + 25, { align: 'center' })

  y += 36

  // ── Questions ──
  y = addSectionTitle(doc, 'Questions & Answers', y)

  questions.forEach((q, i) => {
    if (y > 255) { doc.addPage(); y = 20 }

    // Question number + text
    doc.setFillColor(240, 240, 255)
    doc.roundedRect(14, y, 182, 8, 2, 2, 'F')
    doc.setTextColor(60, 60, 100)
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.text(`Q${i + 1}.`, 17, y + 5.5)
    doc.setFont('helvetica', 'normal')

    const qLines = doc.splitTextToSize(q.question, 160)
    doc.text(qLines, 26, y + 5.5)
    y += 8 + (qLines.length - 1) * 4 + 2

    // MCQ options
    if (q.type === 'mcq' && q.options) {
      q.options.forEach((opt, oi) => {
        if (y > 270) { doc.addPage(); y = 20 }
        const letter = ['A','B','C','D'][oi]
        const isCorrect = letter === q.correct_answer
        const isSelected = answers?.[i] === letter

        if (isCorrect) {
          doc.setFillColor(220, 255, 240)
          doc.roundedRect(20, y - 1, 172, 6, 1, 1, 'F')
          doc.setTextColor(0, 150, 100)
        } else if (isSelected && !isCorrect) {
          doc.setFillColor(255, 235, 235)
          doc.roundedRect(20, y - 1, 172, 6, 1, 1, 'F')
          doc.setTextColor(200, 50, 50)
        } else {
          doc.setTextColor(80, 80, 120)
        }

        doc.setFontSize(8)
        doc.setFont('helvetica', isCorrect ? 'bold' : 'normal')
        const optText = `${letter}. ${opt.replace(/^[A-D]\.\s*/, '')}${isCorrect ? ' ✓' : ''}${isSelected && !isCorrect ? ' ✗' : ''}`
        doc.text(optText, 24, y + 3.5)
        y += 7
      })

      // Explanation
      if (q.explanation) {
        if (y > 270) { doc.addPage(); y = 20 }
        doc.setFillColor(240, 255, 250)
        doc.roundedRect(20, y, 172, 7, 1, 1, 'F')
        doc.setTextColor(0, 130, 90)
        doc.setFontSize(7.5)
        doc.setFont('helvetica', 'italic')
        const expLines = doc.splitTextToSize(`💡 ${q.explanation}`, 165)
        doc.text(expLines[0], 24, y + 4.5)
        y += 10
      }
    }

    // Short answer
    if (q.type === 'short' || q.type === 'formula') {
      if (y > 265) { doc.addPage(); y = 20 }
      doc.setFillColor(245, 245, 255)
      doc.roundedRect(20, y, 172, 7, 1, 1, 'F')
      doc.setTextColor(80, 80, 140)
      doc.setFontSize(7.5)
      doc.setFont('helvetica', 'normal')
      doc.text(`Expected: ${q.answer}`, 24, y + 4.5)
      y += 9

      if (answers?.[i]) {
        const ev = evaluations?.[i]
        doc.setFillColor(ev?.is_correct ? 220 : 255, ev?.is_correct ? 255 : 235, ev?.is_correct ? 240 : 235)
        doc.roundedRect(20, y, 172, 7, 1, 1, 'F')
        doc.setTextColor(ev?.is_correct ? 0 : 180, ev?.is_correct ? 150 : 50, ev?.is_correct ? 100 : 50)
        doc.text(`Your answer: ${answers[i]}${ev ? `  (${ev.score}/100)` : ''}`, 24, y + 4.5)
        y += 9
      }
    }

    y += 4
  })

  // ── Score summary table ──
  if (y > 230) { doc.addPage(); y = 20 }
  y = addSectionTitle(doc, 'Performance Summary', y)

  autoTable(doc, {
    startY: y,
    head: [['Metric', 'Value']],
    body: [
      ['Topic', config?.topic || 'General Engineering'],
      ['Quiz Type', config?.quizType?.toUpperCase() || 'MCQ'],
      ['Difficulty', config?.difficulty || 'Medium'],
      ['Total Questions', String(score?.total || questions.length)],
      ['Correct Answers', String(score?.correct || 0)],
      ['Score', `${pct}%`],
      ['Time Taken', score?.timeTaken ? `${Math.floor(score.timeTaken/60)}m ${score.timeTaken%60}s` : 'N/A'],
      ['Exam Mode', config?.timedMode ? 'Timed Exam' : 'Practice'],
    ],
    theme: 'grid',
    headStyles: { fillColor: [124, 106, 247], textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 8, textColor: [50, 50, 80] },
    alternateRowStyles: { fillColor: [248, 247, 255] },
    margin: { left: 14, right: 14 },
  })

  addFooter(doc)
  doc.save(`StudyBuddy_Quiz_${config?.topic || 'General'}_${new Date().toISOString().split('T')[0]}.pdf`)
}


// ── Export Study Plan ─────────────────────────────────────────────────────────

export const exportStudyPlanPDF = ({ studyPlan, userName = 'Student' }) => {
  const doc = new jsPDF()
  let y = addHeader(doc, 'AI-Generated Study Plan')

  // Intro box
  doc.setFillColor(245, 243, 255)
  doc.roundedRect(14, y, 182, 16, 3, 3, 'F')
  doc.setTextColor(124, 106, 247)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text('✨ Personalized Study Plan', 105, y + 7, { align: 'center' })
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 100, 140)
  doc.text(`Generated for: ${userName}  |  Date: ${new Date().toLocaleDateString()}`, 105, y + 13, { align: 'center' })
  y += 24

  // Weak topics
  if (studyPlan?.weak_topics?.length > 0) {
    y = addSectionTitle(doc, 'Weak Topics to Focus On', y, [247, 106, 106])

    autoTable(doc, {
      startY: y,
      head: [['Topic', 'Accuracy', 'Status']],
      body: studyPlan.weak_topics.map(t => [
        t.topic,
        `${t.accuracy}%`,
        t.accuracy < 40 ? '🔴 Critical' : t.accuracy < 60 ? '🟠 Needs Work' : '🟡 Improving'
      ]),
      theme: 'grid',
      headStyles: { fillColor: [247, 106, 106], textColor: 255, fontSize: 9 },
      bodyStyles: { fontSize: 8, textColor: [50, 50, 80] },
      alternateRowStyles: { fillColor: [255, 248, 248] },
      margin: { left: 14, right: 14 },
    })

    y = doc.lastAutoTable.finalY + 10
  }

  // Due cards
  if (studyPlan?.due_cards_today > 0) {
    if (y > 260) { doc.addPage(); y = 20 }
    doc.setFillColor(220, 255, 240)
    doc.roundedRect(14, y, 182, 10, 2, 2, 'F')
    doc.setTextColor(0, 150, 100)
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.text(`📅 ${studyPlan.due_cards_today} flashcard${studyPlan.due_cards_today > 1 ? 's' : ''} due for review today`, 105, y + 6.5, { align: 'center' })
    y += 16
  }

  // Study plan text
  if (studyPlan?.study_plan) {
    if (y > 240) { doc.addPage(); y = 20 }
    y = addSectionTitle(doc, 'Your Study Schedule', y)

    doc.setTextColor(50, 50, 80)
    doc.setFontSize(8.5)
    doc.setFont('helvetica', 'normal')

    const lines = studyPlan.study_plan.split('\n').filter(l => l.trim())
    lines.forEach(line => {
      if (y > 270) { doc.addPage(); y = 20 }
      const wrapped = doc.splitTextToSize(line, 178)
      wrapped.forEach(wl => {
        if (y > 270) { doc.addPage(); y = 20 }
        // Highlight time blocks
        if (line.match(/\d+:\d+|hour|min|am|pm/i)) {
          doc.setTextColor(124, 106, 247)
          doc.setFont('helvetica', 'bold')
        } else {
          doc.setTextColor(50, 50, 80)
          doc.setFont('helvetica', 'normal')
        }
        doc.text(wl, 16, y)
        y += 5.5
      })
    })
  }

  addFooter(doc)
  doc.save(`StudyBuddy_StudyPlan_${new Date().toISOString().split('T')[0]}.pdf`)
}


// ── Export Progress Report ────────────────────────────────────────────────────

export const exportProgressPDF = ({
  quizHistory,
  fcStats,
  topicStats,
  streak,
  userName = 'Student'
}) => {
  const doc = new jsPDF()
  let y = addHeader(doc, 'Learning Progress Report')

  // Stats summary
  const avgScore = quizHistory?.length
    ? Math.round(quizHistory.reduce((a, b) => a + b.score_percentage, 0) / quizHistory.length)
    : 0

  autoTable(doc, {
    startY: y,
    head: [['Metric', 'Value', 'Metric', 'Value']],
    body: [
      ['Total Quizzes', String(quizHistory?.length || 0), 'Average Score', `${avgScore}%`],
      ['Total Flashcards', String(fcStats?.total || 0), 'Cards Mastered', String(fcStats?.mastered || 0)],
      ['Study Streak', `${streak} days`, 'Due Today', String(fcStats?.due_today || 0)],
    ],
    theme: 'grid',
    headStyles: { fillColor: [124, 106, 247], textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 8.5, textColor: [50, 50, 80] },
    alternateRowStyles: { fillColor: [248, 247, 255] },
    margin: { left: 14, right: 14 },
  })

  y = doc.lastAutoTable.finalY + 12

  // Topic performance
  if (topicStats?.length > 0) {
    y = addSectionTitle(doc, 'Topic Performance', y)

    autoTable(doc, {
      startY: y,
      head: [['Topic', 'Accuracy', 'Questions Attempted', 'Status']],
      body: topicStats.map(t => [
        t.fullTopic || t.topic,
        `${t.accuracy}%`,
        String(t.total),
        t.accuracy >= 80 ? '🟢 Strong' : t.accuracy >= 60 ? '🟡 Good' : '🔴 Weak'
      ]),
      theme: 'grid',
      headStyles: { fillColor: [124, 106, 247], textColor: 255, fontSize: 9 },
      bodyStyles: { fontSize: 8, textColor: [50, 50, 80] },
      alternateRowStyles: { fillColor: [248, 247, 255] },
      margin: { left: 14, right: 14 },
      didDrawCell: (data) => {
        if (data.column.index === 1 && data.row.section === 'body') {
          const acc = parseInt(data.cell.raw)
          if (acc >= 80) doc.setTextColor(0, 150, 100)
          else if (acc >= 60) doc.setTextColor(180, 130, 0)
          else doc.setTextColor(200, 50, 50)
        }
      }
    })

    y = doc.lastAutoTable.finalY + 12
  }

  // Recent quiz history
  if (quizHistory?.length > 0) {
    if (y > 220) { doc.addPage(); y = 20 }
    y = addSectionTitle(doc, 'Recent Quiz History', y)

    autoTable(doc, {
      startY: y,
      head: [['Date', 'Topic', 'Type', 'Difficulty', 'Score', 'Result']],
      body: quizHistory.slice(0, 10).map(a => [
        new Date(a.created_at).toLocaleDateString(),
        a.topic || 'General',
        a.quiz_type.toUpperCase(),
        a.difficulty,
        `${Math.round(a.score_percentage)}%`,
        a.score_percentage >= 80 ? '🟢 Excellent' : a.score_percentage >= 60 ? '🟡 Good' : '🔴 Needs Work'
      ]),
      theme: 'striped',
      headStyles: { fillColor: [124, 106, 247], textColor: 255, fontSize: 8 },
      bodyStyles: { fontSize: 7.5, textColor: [50, 50, 80] },
      margin: { left: 14, right: 14 },
    })
  }

  addFooter(doc)
  doc.save(`StudyBuddy_Progress_${userName.replace(' ', '_')}_${new Date().toISOString().split('T')[0]}.pdf`)
}

// ── Export Document Summary ───────────────────────────────────────────────────

export const exportSummaryPDF = ({ summary, documentName }) => {
  const doc = new jsPDF()
  let y = addHeader(doc, 'Document Summary')

  doc.setFillColor(240, 255, 248)
  doc.roundedRect(14, y, 182, 12, 3, 3, 'F')
  doc.setTextColor(0, 150, 100)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text(`📋 ${documentName}`, 105, y + 8, { align: 'center' })
  y += 20

  doc.setTextColor(50, 50, 80)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')

  const lines = summary.split('\n').filter(l => l.trim())
  lines.forEach(line => {
    if (y > 270) { doc.addPage(); y = 20 }
    if (line.startsWith('**') && line.endsWith('**')) {
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(124, 106, 247)
      doc.setFontSize(10)
      doc.text(line.replace(/\*\*/g, ''), 14, y)
      y += 7
    } else if (line.startsWith('- ') || line.startsWith('• ')) {
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(50, 50, 80)
      doc.setFontSize(8.5)
      const wrapped = doc.splitTextToSize('• ' + line.slice(2), 175)
      wrapped.forEach(wl => {
        if (y > 270) { doc.addPage(); y = 20 }
        doc.text(wl, 18, y)
        y += 5.5
      })
    } else {
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(50, 50, 80)
      doc.setFontSize(8.5)
      const wrapped = doc.splitTextToSize(line, 178)
      wrapped.forEach(wl => {
        if (y > 270) { doc.addPage(); y = 20 }
        doc.text(wl, 14, y)
        y += 5.5
      })
    }
    y += 1
  })

  addFooter(doc)
  doc.save(`StudyBuddy_Summary_${documentName.replace(/\.[^.]+$/, '')}_${new Date().toISOString().split('T')[0]}.pdf`)
}


// ── Export Formula Sheet ──────────────────────────────────────────────────────

export const exportFormulaSheetPDF = ({ formulas, documentName }) => {
  const doc = new jsPDF()
  let y = addHeader(doc, 'Formula Sheet')

  doc.setFillColor(255, 248, 235)
  doc.roundedRect(14, y, 182, 12, 3, 3, 'F')
  doc.setTextColor(180, 100, 0)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text(`🧮 ${documentName}`, 105, y + 8, { align: 'center' })
  y += 20

  const sections = formulas.split('---').filter(s => s.trim())

  sections.forEach(section => {
    if (y > 250) { doc.addPage(); y = 20 }

    const lines = section.trim().split('\n').filter(l => l.trim())
    if (!lines.length) return

    // Section box
    doc.setFillColor(255, 250, 240)
    doc.roundedRect(14, y - 2, 182, Math.min(lines.length * 6 + 8, 60), 3, 3, 'F')

    lines.forEach(line => {
      if (y > 270) { doc.addPage(); y = 20 }

      if (line.startsWith('**') && line.endsWith('**')) {
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(180, 100, 0)
        doc.setFontSize(10)
        doc.text(line.replace(/\*\*/g, ''), 18, y)
        y += 7
      } else if (line.toLowerCase().startsWith('formula:')) {
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(124, 106, 247)
        doc.setFontSize(10)
        const wrapped = doc.splitTextToSize(line, 170)
        wrapped.forEach(wl => { doc.text(wl, 18, y); y += 6 })
      } else {
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(80, 60, 40)
        doc.setFontSize(8.5)
        const wrapped = doc.splitTextToSize(line, 170)
        wrapped.forEach(wl => { doc.text(wl, 18, y); y += 5.5 })
      }
    })
    y += 8
  })

  addFooter(doc)
  doc.save(`StudyBuddy_Formulas_${documentName.replace(/\.[^.]+$/, '')}_${new Date().toISOString().split('T')[0]}.pdf`)
}